### ISSUE TITLE
Refreshing image pull periodically

### ISSUE THREAD

**Issue by sindelsch** [Dalvany/dalvany-image-panel#45] opened 2022-05-11 11:05 UTC
Hi,

I am trying to display images in your panel via urls stored in a mysql database.
It is possible to refresh the query periodically, but the shown pictures are only refreshed when I refresh the browser (The step when the images are pulled via the url).

Would it be possible to also do this periodically? Maybe even connected to running the query.

Thanks in advance!

**Comment by Dalvany** [comment] 2022-05-12 13:02
Hello @sindelsch I don't think it is possible, when query is rerun, grafana tell my panel to redraw accordingly.

For your second point, you can tell grafana to refresh periodically using the top right combobox.
![image](https://user-images.githubusercontent.com/9901407/168080743-1dd5ae93-f416-487b-b8bb-e48cb9777900.png)

Does this fit your usecase ?

**Comment by Dalvany** [comment] 2022-05-21 12:29
Could it be because of some cache ?
I have another question, just to be sure of how things are set up. You have URL stored in your database, in Grafana you have a data source that queries the database and the panel use that to display image ?

**Comment by Dalvany** [comment] 2022-08-15 13:42
@sindelsch I can't reproduce the bug, I try setting up a webservice that serves random images, reduce grafana's refresh to 5s and it works.
Can you check if there is some cache involved ?

**Comment by Dalvany** [comment] 2023-10-29 08:44
I close this issue.

**Closed by Dalvany** 2023-10-29 08:44 UTC
