### ISSUE TITLE
Panel not visible on visualizations list

### ISSUE THREAD

**Issue by GarbatyGrabarz** [Dalvany/dalvany-image-panel#30] opened 2021-06-11 17:17 UTC
The plugin shows on the plugins list but when I want to add a panel it does not appear on the visualizations list
I have Grafana v8.0.1 and plugin in version 2.2.1

**Comment by Dalvany** [comment] 2021-06-11 18:10
Hello @GarbatyGrabarz , I believe it's because since grafana 8 all plugins must be signed (you can checked inside grafana in the plugin management page, there should be a warning saying that `dalvany-image-panel` is disabled because it's unsigned). There's two solutions right now :
* use [allow_loading_unsigned_plugins](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins) (use GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS environment variable if you're using docker)
* or wait for [this pull request](https://github.com/grafana/grafana-plugin-repository/pull/948) to be merge (next version will be signed)

**Comment by Dalvany** [comment] 2021-06-11 19:12
I might have answered too fast, when trying, grafana seem to have signed the plugin.
Do you use docker and do you mount a data volume ?

**Comment by GarbatyGrabarz** [comment] 2021-06-11 19:50
Sorry, I'm very green so I am not even sure if I answer correctly :/
I do not use docker. Grafana is standing on Windows 10
I don't know where to find plugins configuration. Is this something in Grafana's GUI or is it a file?
There is no `dist` inside `dalvany-image-panel`

**Comment by Dalvany** [comment] 2021-06-11 19:56
Oh sorry, in the left menu, do you see a 'cog', like in this capture ?
![image](https://user-images.githubusercontent.com/9901407/121742273-e73df280-caff-11eb-80e7-87d006af1af3.png)

**Comment by GarbatyGrabarz** [comment] 2021-06-11 19:58
Yes. Dynamic image panel is listed there. Signed too

**Comment by Dalvany** [comment] 2021-06-11 20:08
I'll try to reproduce on windows.

**Comment by Dalvany** [comment] 2021-06-11 20:12
It seems to work
![image](https://user-images.githubusercontent.com/9901407/121743701-08074780-cb02-11eb-93e4-a5b10a7d5e2f.png)
Can you access grafana logs ?

**Comment by GarbatyGrabarz** [comment] 2021-06-11 21:17
I really don't know how to explain this but it started to show up on some dashboards and not on others. I tried to make a screenshot but now it appears on all dashboards. Sorry for the trouble :D

**Comment by GarbatyGrabarz** [comment] 2021-06-11 21:21
OK. I did not lose my mind. Gone again!
![image](https://user-images.githubusercontent.com/71323810/121749853-a64bdb00-cb0b-11eb-95c5-545e93c24cbb.png)

**Comment by underdog** [comment] 2021-06-12 02:56
I'm running grafana beta3 and the plugin shows up in the list but is not showing up within the panels

**Comment by Dalvany** [comment] 2021-06-12 09:16
@GarbatyGrabarz it's really strange. What browser do you use ? Can you access your browser's developper tools (if it has any), and see in the javascript console if there's error ?
@underdog I see in your capture that it's still the `table` that is selected, so it's its options that are shown. If you select "Dynamic image panel" you should see at least three section like in the capture in  [this README for v2.2.1](https://github.com/Dalvany/dalvany-image-panel/blob/v2.2.0/README.MD)

**Comment by Dalvany** [comment] 2021-06-12 09:19
@GarbatyGrabarz also, do you have other non official plugins and does the bug affect them too ?

**Comment by underdog** [comment] 2021-06-12 15:20
> @GarbatyGrabarz it's really strange. What browser do you use ? Can you access your browser's developper tools (if it has any), and see in the javascript console if there's error ?
> @underdog I see in your capture that it's still the `table` that is selected, so it's its options that are shown. If you select "Dynamic image panel" you should see at least three section like in the capture in [this README for v2.2.1](https://github.com/Dalvany/dalvany-image-panel/blob/v2.2.0/README.MD)

very strange.  it wasn't in the drop down selections list last night, but this morning it shows up.

I'll keep an eye on this and see if it does it again

**Comment by GarbatyGrabarz** [comment] 2021-06-12 17:23
I have few other plugins but I have never observed this before. I am using Chrome but for now it will be difficult to check the logs for error since the panel mischievously appears every time

**Comment by Dalvany** [comment] 2021-06-13 08:42
Ok, thank you, I'll keep this issue open for some time.

**Comment by Dalvany** [comment] 2021-09-04 18:15
I close this issue. If it happens again, do not hesitate to open a new one.

**Closed by Dalvany** 2021-09-04 18:15 UTC
Labels: bug
